// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMStudio.Data;

namespace PMStudio.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            RoleId = "B8A39BD0-1C75-4660-9749-0B47328E0720"
                        },
                        new
                        {
                            UserId = "B20F8CEE-4341-46CC-84F7-FB75D269A2E4",
                            RoleId = "5F2A7EDB-703F-479D-BFF9-F19164A66E3A"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PMStudio.Data.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "B8A39BD0-1C75-4660-9749-0B47328E0720",
                            ConcurrencyStamp = "77bfd359-1824-4f8a-a9e1-1ac844cf0ccd",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "5F2A7EDB-703F-479D-BFF9-F19164A66E3A",
                            ConcurrencyStamp = "1f67ee81-6d21-4bfb-b4d3-abc814ae2ba4",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("PMStudio.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5692489b-71a5-4df7-ad0c-77e3b55b530f",
                            CreatedOn = new DateTime(2020, 12, 26, 20, 58, 53, 119, DateTimeKind.Local).AddTicks(8677),
                            Email = "pepibasket@yahoo.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "PEPIBASKET@YAHOO.COM",
                            NormalizedUserName = "PEPIBASKET@YAHOO.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHj8dN9Eb0p24FpGSZfdAtZzXG0VEzf4tgPpy9xYOGD5R/4qMCva5STZfArEw18K7A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e305a2f-1985-4521-86d4-864eef913498",
                            TwoFactorEnabled = false,
                            UserName = "pepibasket@yahoo.com"
                        },
                        new
                        {
                            Id = "B20F8CEE-4341-46CC-84F7-FB75D269A2E4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "527bdac9-ea12-45de-9a1c-b4afbd318943",
                            CreatedOn = new DateTime(2020, 12, 26, 20, 58, 53, 142, DateTimeKind.Local).AddTicks(4349),
                            Email = "vasa@gmail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "VASA@GMAIL.COM",
                            NormalizedUserName = "VASA@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGjfOsjAaxduany0KE88wN4rU4abWkBf2IIlDgiOj/mbaF7vTTvdvckvf4anlROEYw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8b38c9e9-58cb-4143-9b69-906a28bfd791",
                            TwoFactorEnabled = false,
                            UserName = "vasa@gmail.com"
                        });
                });

            modelBuilder.Entity("PMStudio.Data.Models.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AddedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("RemoteImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = "d43e3dd4-4f55-4c84-92b2-94c4b84b924a",
                            AddedByUserId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            CreatedOn = new DateTime(2020, 12, 27, 4, 58, 53, 145, DateTimeKind.Utc).AddTicks(3338),
                            Extension = "jpg",
                            PropertyId = 1
                        },
                        new
                        {
                            Id = "8eda1d0e-0496-41b2-83bf-c9e26049f569",
                            AddedByUserId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            CreatedOn = new DateTime(2020, 12, 27, 4, 58, 53, 145, DateTimeKind.Utc).AddTicks(5486),
                            Extension = "jpg",
                            PropertyId = 2
                        },
                        new
                        {
                            Id = "1db364b0-cae7-4ba2-b5c9-19e88dc91347",
                            AddedByUserId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            CreatedOn = new DateTime(2020, 12, 27, 4, 58, 53, 145, DateTimeKind.Utc).AddTicks(5690),
                            Extension = "jpg",
                            PropertyId = 3
                        },
                        new
                        {
                            Id = "c04a661f-96be-4b9f-ab37-66a7b9e4bd2a",
                            AddedByUserId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            CreatedOn = new DateTime(2020, 12, 27, 4, 58, 53, 145, DateTimeKind.Utc).AddTicks(5887),
                            Extension = "jpg",
                            PropertyId = 4
                        },
                        new
                        {
                            Id = "31a41705-ec71-4839-8e83-a52d07574c5b",
                            AddedByUserId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            CreatedOn = new DateTime(2020, 12, 27, 4, 58, 53, 145, DateTimeKind.Utc).AddTicks(6144),
                            Extension = "jpg",
                            PropertyId = 5
                        },
                        new
                        {
                            Id = "9ff1e3ac-4af2-4fe6-9bdc-063121f86e82",
                            AddedByUserId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            CreatedOn = new DateTime(2020, 12, 27, 4, 58, 53, 145, DateTimeKind.Utc).AddTicks(6331),
                            Extension = "jpg",
                            PropertyId = 6
                        });
                });

            modelBuilder.Entity("PMStudio.Data.Models.MaintenanceService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PropertyId");

                    b.HasIndex("VendorId");

                    b.ToTable("MaintenanceServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Name = "Bathroom repair",
                            PropertyId = 1,
                            ServiceDate = new DateTime(2021, 11, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            VendorId = 3
                        });
                });

            modelBuilder.Entity("PMStudio.Data.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ManagerId");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "100 Marguerite Ave, Unit 2, Newport Beach, CA 92660",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Newport Condo",
                            Owner = "WestCoast Investments",
                            Size = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "1822 Redhill, Irvine, Ca 92112",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Irvine Warehouse",
                            Owner = "Logistics Solutions LLC",
                            Size = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Address = "12252 Wood Canyon Dr., CA 92229",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Aliso Viejo House",
                            Owner = "Home Properties LLC",
                            Size = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Address = "37 Baranca, Irvine, CA 92229",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Irvine Valley Home",
                            Owner = "Home Properties LLC",
                            Size = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = "37 Newport Dr, Newport Beach, CA 92879",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Newport Mansion",
                            Owner = "Home Properties LLC",
                            Size = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Address = "818 Johson Str, Long Beach, CA 81447",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Storage Place",
                            Owner = "Rental Assets LLC",
                            Size = 0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("PMStudio.Data.Models.PropertyVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("VendorId");

                    b.ToTable("PropertyVendors");
                });

            modelBuilder.Entity("PMStudio.Data.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PMStudio.Data.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeasePeriod")
                        .HasColumnType("int");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ManagerId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeasePeriod = 12,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "John Smith",
                            PropertyId = 1,
                            Rate = 3500
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LeasePeriod = 16,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Kristina Ivanova",
                            PropertyId = 3,
                            Rate = 1500
                        });
                });

            modelBuilder.Entity("PMStudio.Data.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ManagerId");

                    b.ToTable("Vendors");

                    b.HasData(
                        new
                        {
                            Id = 12,
                            Address = "2020 Von Karman Ave, Irvine, CA 92660",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "help@cox.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Cox",
                            Phone = "714-122-1338",
                            Trade = "Telephones"
                        },
                        new
                        {
                            Id = 13,
                            Address = "2020 Von Karman Ave, Irvine, CA 92660",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "help@at&t.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "AT&T",
                            Phone = "714-511-5878",
                            Trade = "Internet"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1414 Von Karman Ave, Irvine, CA 92660",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "service@bestplumbing.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Best Plumbing Specialists",
                            Phone = "714-111-4147",
                            Trade = "Plumbing"
                        },
                        new
                        {
                            Id = 4,
                            Address = "218 Michelson Ave, Irvine, CA 92660",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@cleaningcrew.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Cleaning Crew",
                            Phone = "714-111-5151",
                            Trade = "Cleaning"
                        },
                        new
                        {
                            Id = 5,
                            Address = "100 12th Str, Costa Mesa, CA 92414",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nick@fivestar.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Five Star Elevator",
                            Phone = "914-747-1100",
                            Trade = "Elevator Repairs"
                        },
                        new
                        {
                            Id = 6,
                            Address = "PO Box 104, Los Angeles, CA 95114",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "moving@movingforfun.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Moving For Fun",
                            Phone = "949-555-5511",
                            Trade = "Moving Services"
                        },
                        new
                        {
                            Id = 7,
                            Address = "110 Newport Dr, Newport Beach, CA 92418",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "help@pestexterminator.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "PestExterminators",
                            Phone = "949-142-2284",
                            Trade = "Pest Control"
                        },
                        new
                        {
                            Id = 8,
                            Address = "22 6th Ave, Los Angeles, CA 94422",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@westex.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Westex",
                            Phone = "818-521-4840",
                            Trade = "HVAC"
                        },
                        new
                        {
                            Id = 9,
                            Address = "22th Ave, Los Angeles, CA 94422",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@modern.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Modern",
                            Phone = "818-111-9951",
                            Trade = "Interior Design"
                        },
                        new
                        {
                            Id = 10,
                            Address = "2151 Baranca, Santa Ana, CA 92650",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "info@securitycontrol.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "Security Control LLC",
                            Phone = "949-013-0103",
                            Trade = "Alarm"
                        },
                        new
                        {
                            Id = 11,
                            Address = "333 Marguerite, Long Beach, CA 92650",
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johnjohnson@gmail.com",
                            IsDeleted = false,
                            ManagerId = "088bbcf3-2259-4570-93b8-cffbf7a064e5",
                            Name = "John&John Co.",
                            Phone = "714-214-3510",
                            Trade = "Painting"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("PMStudio.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PMStudio.Data.Models.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PMStudio.Data.Models.ApplicationUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("PMStudio.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMStudio.Data.Models.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PMStudio.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PMStudio.Data.Models.Image", b =>
                {
                    b.HasOne("PMStudio.Data.Models.ApplicationUser", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId");

                    b.HasOne("PMStudio.Data.Models.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PMStudio.Data.Models.MaintenanceService", b =>
                {
                    b.HasOne("PMStudio.Data.Models.Property", "Property")
                        .WithMany("MaintenanceServices")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMStudio.Data.Models.Vendor", "Vendor")
                        .WithMany("MaintenanceServices")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PMStudio.Data.Models.Property", b =>
                {
                    b.HasOne("PMStudio.Data.Models.ApplicationUser", "Manager")
                        .WithMany("Properties")
                        .HasForeignKey("ManagerId");

                    b.HasOne("PMStudio.Data.Models.Tenant", "Tenant")
                        .WithOne("Property")
                        .HasForeignKey("PMStudio.Data.Models.Property", "TenantId");

                    b.Navigation("Manager");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PMStudio.Data.Models.PropertyVendor", b =>
                {
                    b.HasOne("PMStudio.Data.Models.Property", "Property")
                        .WithMany("PropertyVendors")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMStudio.Data.Models.Vendor", "Vendor")
                        .WithMany("PropertyVendors")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PMStudio.Data.Models.Tenant", b =>
                {
                    b.HasOne("PMStudio.Data.Models.ApplicationUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PMStudio.Data.Models.Vendor", b =>
                {
                    b.HasOne("PMStudio.Data.Models.ApplicationUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("PMStudio.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Properties");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("PMStudio.Data.Models.Property", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("MaintenanceServices");

                    b.Navigation("PropertyVendors");
                });

            modelBuilder.Entity("PMStudio.Data.Models.Tenant", b =>
                {
                    b.Navigation("Property");
                });

            modelBuilder.Entity("PMStudio.Data.Models.Vendor", b =>
                {
                    b.Navigation("MaintenanceServices");

                    b.Navigation("PropertyVendors");
                });
#pragma warning restore 612, 618
        }
    }
}
